name: Terraform Deploy

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - '**'
  #     - main   
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  terraform:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write
      id-token: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
