name: Docker image
 
on:
  workflow_dispatch:
 
env:
  AWS_REGION: ap-south-1
  ROLE_TO_ASSUME: arn:aws:iam::173003893026:role/github-actions-role-usecase-1
  ECR_REPO: myrepo
     
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ap-south-1

    - name: Create ECR repository (if not exists)
      run: |
              aws ecr describe-repositories --repository-names myrepo --region ap-south-1 || \
              aws ecr create-repository --repository-name myrepo --region ap-south-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
 
    - name: Build, tag, and push image to ECR
      run: |
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest"
        docker build -t $IMAGE_URI ./app
        docker push $IMAGE_URI
        echo "image_uri=$IMAGE_URI" >> $GITHUB_ENV
